In [2]:
import pandas as pd 
import numpy as np
from sklearn import tree
from sklearn.preprocessing import StandardScaler
import sklearn.metrics 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
import sklearn.metrics as metrics
import os
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [3]:
df_train=pd.read_csv('train.csv')

In [4]:
df_test=pd.read_csv('test.csv')

In [5]:
df_train[['PassengerId', 'Survived', 'Pclass']] = df_train[['PassengerId', 'Survived', 'Pclass']].astype("object")

numeric_features = ['Age', 'SibSp']
  
categoric_features = ['Pclass','Sex']
  
preprocessed_df_train = df_train[["Survived"] + numeric_features + categoric_features]

preprocessed_df_train = preprocessed_df_train.assign(Age = preprocessed_df_train[["Age"]].fillna(preprocessed_df_train["Age"].median()))

preprocessed_df_train = pd.get_dummies(data = preprocessed_df_train, columns = ["Pclass", "Sex"], drop_first=True)

In [6]:
y_vec_train = preprocessed_df_train["Survived"].astype("int") 
X_mat_train = preprocessed_df_train.drop(["Survived"],axis=1) 

In [7]:
decision_tree_model = tree.DecisionTreeClassifier()
decision_tree_model.fit(X=X_mat_train, y=y_vec_train)

DecisionTreeClassifier()

In [8]:
df_test[['PassengerId', 'Pclass']] = df_test[['PassengerId', 'Pclass']].astype("object")

numeric_features = ['Age', 'SibSp']
  
categoric_features = ['Pclass','Sex']
  
preprocessed_df_test = df_test[numeric_features + categoric_features]

preprocessed_df_test = preprocessed_df_test.assign(Age = preprocessed_df_test[["Age"]].fillna(preprocessed_df_test["Age"].median()))

preprocessed_df_test = pd.get_dummies(data = preprocessed_df_test, columns = ["Pclass", "Sex"], drop_first=True)

In [12]:
X_mat_test = preprocessed_df_test
y_pred_test = decision_tree_model.predict(X = X_mat_test) 
y_vec_test = y_pred_test.astype("int") 

In [13]:
print(np.round(accuracy_score(y_vec_test, y_pred_test),3)) 

1.0


In [14]:
np.round(np.mean(cross_val_score(decision_tree_model, y_vec_test, y_pred_test)),3)

C:\Users\yoval\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\yoval\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\yoval\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 898, in fit
    super().fit(
  File "C:\Users\yoval\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 156, in fit
    X, y = self._validate_data(X, y,
  File "C:\Users\yoval\anaconda3\lib\site-packages\sklearn\base.py", line 430, in _validate_data
    X = check_array(X, **check_X_params)
  File "C:\Users\yoval\anaconda3\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\yoval\anaconda3\lib\site-packages\sklearn\utils\

nan

In [64]:
metrics.confusion_matrix(y_vec_train,y_pred_test)

array([[528,  21],
       [ 66, 276]], dtype=int64)

In [65]:
np.round(metrics.precision_score(y_vec_train,y_pred_test),2)

0.93

In [55]:
np.round(metrics.recall_score(y_vec_train,y_pred_test),2)

0.81

In [30]:
y_pred_test

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,

In [31]:
PassengerId = df_test["PassengerId"]

result = pd.Series(y_pred_test) 

In [32]:
pred_df = pd.concat([PassengerId , result], axis = 1)

In [73]:
pred_df.to_csv("pred_df.csv")

In [33]:
norm_scaler = StandardScaler()
X_mat_norm = norm_scaler.fit_transform(X_mat_train)

In [34]:
y_target = preprocessed_df_train

log_model = LogisticRegression()

log_model_norm = LogisticRegression()

log_model.fit(X=X_mat_train, y=y_vec_train)

log_model_norm.fit(X=X_mat_norm, y=y_vec_train)

LogisticRegression()

In [35]:
X_mat_test = preprocessed_df_test
Y_pred_log = log_model.predict(X = X_mat_test)

In [36]:
Y_pred_log

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [37]:
PassengerId = df_test["PassengerId"]
result_log = pd.Series(Y_pred_log) 

In [38]:
pred_df_log = pd.concat([PassengerId , result_log], axis = 1)

In [93]:
pred_df_log.to_csv("pred_df_log.csv")